;; Generated by WHAT-THE-FFI  (do not edit)
(in-package #:vg)
(declaim (optimize (speed 3) (safety 0) (debug 0)))
(defctype xfixnum :int)
(export 'xfixnum)
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:448:9)
;;
(defctype blend-mode xfixnum);; was _VGBlendMode
(export 'blend-mode)
(defparameter blend-src #x2000 );; VG_BLEND_SRC
(export 'blend-src)
(defparameter blend-src-over #x2001 );; VG_BLEND_SRC_OVER
(export 'blend-src-over)
(defparameter blend-dst-over #x2002 );; VG_BLEND_DST_OVER
(export 'blend-dst-over)
(defparameter blend-src-in #x2003 );; VG_BLEND_SRC_IN
(export 'blend-src-in)
(defparameter blend-dst-in #x2004 );; VG_BLEND_DST_IN
(export 'blend-dst-in)
(defparameter blend-multiply #x2005 );; VG_BLEND_MULTIPLY
(export 'blend-multiply)
(defparameter blend-screen #x2006 );; VG_BLEND_SCREEN
(export 'blend-screen)
(defparameter blend-darken #x2007 );; VG_BLEND_DARKEN
(export 'blend-darken)
(defparameter blend-lighten #x2008 );; VG_BLEND_LIGHTEN
(export 'blend-lighten)
(defparameter blend-additive #x2009 );; VG_BLEND_ADDITIVE
(export 'blend-additive)
;; (defparameter blend-mode-force-size #x7FFFFFFF );; VG_BLEND_MODE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:431:9)
;;
(defctype image-mode xfixnum);; was _VGImageMode
(export 'image-mode)
(defparameter draw-image-normal #x1F00 );; VG_DRAW_IMAGE_NORMAL
(export 'draw-image-normal)
(defparameter draw-image-multiply #x1F01 );; VG_DRAW_IMAGE_MULTIPLY
(export 'draw-image-multiply)
(defparameter draw-image-stencil #x1F02 );; VG_DRAW_IMAGE_STENCIL
(export 'draw-image-stencil)
;; (defparameter image-mode-force-size #x7FFFFFFF );; VG_IMAGE_MODE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:423:9)
;;
(defctype image-param-type xfixnum);; was _VGImageParamType
(export 'image-param-type)
(defparameter image-format #x1E00 );; VG_IMAGE_FORMAT
(export 'image-format)
(defparameter image-width #x1E01 );; VG_IMAGE_WIDTH
(export 'image-width)
(defparameter image-height #x1E02 );; VG_IMAGE_HEIGHT
(export 'image-height)
;; (defparameter image-param-type-force-size #x7FFFFFFF );; VG_IMAGE_PARAM_TYPE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:415:9)
;;
(defctype image-quality xfixnum);; was _VGImageQuality
(export 'image-quality)
(defparameter image-quality-nonantialiased #x1 );; VG_IMAGE_QUALITY_NONANTIALIASED
(export 'image-quality-nonantialiased)
(defparameter image-quality-faster #x2 );; VG_IMAGE_QUALITY_FASTER
(export 'image-quality-faster)
(defparameter image-quality-better #x4 );; VG_IMAGE_QUALITY_BETTER
(export 'image-quality-better)
;; (defparameter image-quality-force-size #x7FFFFFFF );; VG_IMAGE_QUALITY_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:346:9)
;;
(defctype color-ramp-spread-mode xfixnum);; was _VGColorRampSpreadMode
(export 'color-ramp-spread-mode)
(defparameter color-ramp-spread-pad #x1C00 );; VG_COLOR_RAMP_SPREAD_PAD
(export 'color-ramp-spread-pad)
(defparameter color-ramp-spread-repeat #x1C01 );; VG_COLOR_RAMP_SPREAD_REPEAT
(export 'color-ramp-spread-repeat)
(defparameter color-ramp-spread-reflect #x1C02 );; VG_COLOR_RAMP_SPREAD_REFLECT
(export 'color-ramp-spread-reflect)
;; (defparameter color-ramp-spread-mode-force-size #x7FFFFFFF );; VG_COLOR_RAMP_SPREAD_MODE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:317:9)
;;
(defctype paint-param-type xfixnum);; was _VGPaintParamType
(export 'paint-param-type)
(defparameter paint-type #x1A00 );; VG_PAINT_TYPE
(export 'paint-type)
(defparameter paint-color #x1A01 );; VG_PAINT_COLOR
(export 'paint-color)
(defparameter paint-color-ramp-spread-mode #x1A02 );; VG_PAINT_COLOR_RAMP_SPREAD_MODE
(export 'paint-color-ramp-spread-mode)
(defparameter paint-color-ramp-premultiplied #x1A07 );; VG_PAINT_COLOR_RAMP_PREMULTIPLIED
(export 'paint-color-ramp-premultiplied)
(defparameter paint-color-ramp-stops #x1A03 );; VG_PAINT_COLOR_RAMP_STOPS
(export 'paint-color-ramp-stops)
(defparameter paint-linear-gradient #x1A04 );; VG_PAINT_LINEAR_GRADIENT
(export 'paint-linear-gradient)
(defparameter paint-radial-gradient #x1A05 );; VG_PAINT_RADIAL_GRADIENT
(export 'paint-radial-gradient)
(defparameter paint-pattern-tiling-mode #x1A06 );; VG_PAINT_PATTERN_TILING_MODE
(export 'paint-pattern-tiling-mode)
;; (defparameter paint-param-type-force-size #x7FFFFFFF );; VG_PAINT_PARAM_TYPE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:337:9)
;;
(defctype paint-type xfixnum);; was _VGPaintType
(export 'paint-type)
(defparameter paint-type-color #x1B00 );; VG_PAINT_TYPE_COLOR
(export 'paint-type-color)
(defparameter paint-type-linear-gradient #x1B01 );; VG_PAINT_TYPE_LINEAR_GRADIENT
(export 'paint-type-linear-gradient)
(defparameter paint-type-radial-gradient #x1B02 );; VG_PAINT_TYPE_RADIAL_GRADIENT
(export 'paint-type-radial-gradient)
(defparameter paint-type-pattern #x1B03 );; VG_PAINT_TYPE_PATTERN
(export 'paint-type-pattern)
;; (defparameter paint-type-force-size #x7FFFFFFF );; VG_PAINT_TYPE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:303:9)
;;
(defctype fill-rule xfixnum);; was _VGFillRule
(export 'fill-rule)
(defparameter even-odd #x1900 );; VG_EVEN_ODD
(export 'even-odd)
(defparameter non-zero #x1901 );; VG_NON_ZERO
(export 'non-zero)
;; (defparameter fill-rule-force-size #x7FFFFFFF );; VG_FILL_RULE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:295:9)
;;
(defctype join-style xfixnum);; was _VGJoinStyle
(export 'join-style)
(defparameter join-miter #x1800 );; VG_JOIN_MITER
(export 'join-miter)
(defparameter join-round #x1801 );; VG_JOIN_ROUND
(export 'join-round)
(defparameter join-bevel #x1802 );; VG_JOIN_BEVEL
(export 'join-bevel)
;; (defparameter join-style-force-size #x7FFFFFFF );; VG_JOIN_STYLE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:287:9)
;;
(defctype cap-style xfixnum);; was _VGCapStyle
(export 'cap-style)
(defparameter cap-butt #x1700 );; VG_CAP_BUTT
(export 'cap-butt)
(defparameter cap-round #x1701 );; VG_CAP_ROUND
(export 'cap-round)
(defparameter cap-square #x1702 );; VG_CAP_SQUARE
(export 'cap-square)
;; (defparameter cap-style-force-size #x7FFFFFFF );; VG_CAP_STYLE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:258:9)
;;
(defctype path-capabilities xfixnum);; was _VGPathCapabilities
(export 'path-capabilities)
(defparameter path-capability-append-from #x1 );; VG_PATH_CAPABILITY_APPEND_FROM
(export 'path-capability-append-from)
(defparameter path-capability-append-to #x2 );; VG_PATH_CAPABILITY_APPEND_TO
(export 'path-capability-append-to)
(defparameter path-capability-modify #x4 );; VG_PATH_CAPABILITY_MODIFY
(export 'path-capability-modify)
(defparameter path-capability-transform-from #x8 );; VG_PATH_CAPABILITY_TRANSFORM_FROM
(export 'path-capability-transform-from)
(defparameter path-capability-transform-to #x10 );; VG_PATH_CAPABILITY_TRANSFORM_TO
(export 'path-capability-transform-to)
(defparameter path-capability-interpolate-from #x20 );; VG_PATH_CAPABILITY_INTERPOLATE_FROM
(export 'path-capability-interpolate-from)
(defparameter path-capability-interpolate-to #x40 );; VG_PATH_CAPABILITY_INTERPOLATE_TO
(export 'path-capability-interpolate-to)
(defparameter path-capability-path-length #x80 );; VG_PATH_CAPABILITY_PATH_LENGTH
(export 'path-capability-path-length)
(defparameter path-capability-point-along-path #x100 );; VG_PATH_CAPABILITY_POINT_ALONG_PATH
(export 'path-capability-point-along-path)
(defparameter path-capability-tangent-along-path #x200 );; VG_PATH_CAPABILITY_TANGENT_ALONG_PATH
(export 'path-capability-tangent-along-path)
(defparameter path-capability-path-bounds #x400 );; VG_PATH_CAPABILITY_PATH_BOUNDS
(export 'path-capability-path-bounds)
(defparameter path-capability-path-transformed-bounds #x800 );; VG_PATH_CAPABILITY_PATH_TRANSFORMED_BOUNDS
(export 'path-capability-path-transformed-bounds)
(defparameter path-capability-all #xFFF );; VG_PATH_CAPABILITY_ALL
(export 'path-capability-all)
;; (defparameter path-capabilities-force-size #x7FFFFFFF );; VG_PATH_CAPABILITIES_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:229:9)
;;
(defctype path-command xfixnum);; was _VGPathCommand
(export 'path-command)
(defparameter move-to-abs #x2 );; VG_MOVE_TO_ABS
(export 'move-to-abs)
(defparameter move-to-rel #x3 );; VG_MOVE_TO_REL
(export 'move-to-rel)
(defparameter line-to-abs #x4 );; VG_LINE_TO_ABS
(export 'line-to-abs)
(defparameter line-to-rel #x5 );; VG_LINE_TO_REL
(export 'line-to-rel)
(defparameter hline-to-abs #x6 );; VG_HLINE_TO_ABS
(export 'hline-to-abs)
(defparameter hline-to-rel #x7 );; VG_HLINE_TO_REL
(export 'hline-to-rel)
(defparameter vline-to-abs #x8 );; VG_VLINE_TO_ABS
(export 'vline-to-abs)
(defparameter vline-to-rel #x9 );; VG_VLINE_TO_REL
(export 'vline-to-rel)
(defparameter quad-to-abs #xA );; VG_QUAD_TO_ABS
(export 'quad-to-abs)
(defparameter quad-to-rel #xB );; VG_QUAD_TO_REL
(export 'quad-to-rel)
(defparameter cubic-to-abs #xC );; VG_CUBIC_TO_ABS
(export 'cubic-to-abs)
(defparameter cubic-to-rel #xD );; VG_CUBIC_TO_REL
(export 'cubic-to-rel)
(defparameter squad-to-abs #xE );; VG_SQUAD_TO_ABS
(export 'squad-to-abs)
(defparameter squad-to-rel #xF );; VG_SQUAD_TO_REL
(export 'squad-to-rel)
(defparameter scubic-to-abs #x10 );; VG_SCUBIC_TO_ABS
(export 'scubic-to-abs)
(defparameter scubic-to-rel #x11 );; VG_SCUBIC_TO_REL
(export 'scubic-to-rel)
(defparameter sccwarc-to-abs #x12 );; VG_SCCWARC_TO_ABS
(export 'sccwarc-to-abs)
(defparameter sccwarc-to-rel #x13 );; VG_SCCWARC_TO_REL
(export 'sccwarc-to-rel)
(defparameter scwarc-to-abs #x14 );; VG_SCWARC_TO_ABS
(export 'scwarc-to-abs)
(defparameter scwarc-to-rel #x15 );; VG_SCWARC_TO_REL
(export 'scwarc-to-rel)
(defparameter lccwarc-to-abs #x16 );; VG_LCCWARC_TO_ABS
(export 'lccwarc-to-abs)
(defparameter lccwarc-to-rel #x17 );; VG_LCCWARC_TO_REL
(export 'lccwarc-to-rel)
(defparameter lcwarc-to-abs #x18 );; VG_LCWARC_TO_ABS
(export 'lcwarc-to-abs)
(defparameter lcwarc-to-rel #x19 );; VG_LCWARC_TO_REL
(export 'lcwarc-to-rel)
;; (defparameter path-command-force-size #x7FFFFFFF );; VG_PATH_COMMAND_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:209:9)
;;
(defctype path-segment xfixnum);; was _VGPathSegment
(export 'path-segment)
(defparameter close-path #x0 );; VG_CLOSE_PATH
(export 'close-path)
(defparameter move-to #x2 );; VG_MOVE_TO
(export 'move-to)
(defparameter line-to #x4 );; VG_LINE_TO
(export 'line-to)
(defparameter hline-to #x6 );; VG_HLINE_TO
(export 'hline-to)
(defparameter vline-to #x8 );; VG_VLINE_TO
(export 'vline-to)
(defparameter quad-to #xA );; VG_QUAD_TO
(export 'quad-to)
(defparameter cubic-to #xC );; VG_CUBIC_TO
(export 'cubic-to)
(defparameter squad-to #xE );; VG_SQUAD_TO
(export 'squad-to)
(defparameter scubic-to #x10 );; VG_SCUBIC_TO
(export 'scubic-to)
(defparameter sccwarc-to #x12 );; VG_SCCWARC_TO
(export 'sccwarc-to)
(defparameter scwarc-to #x14 );; VG_SCWARC_TO
(export 'scwarc-to)
(defparameter lccwarc-to #x16 );; VG_LCCWARC_TO
(export 'lccwarc-to)
(defparameter lcwarc-to #x18 );; VG_LCWARC_TO
(export 'lcwarc-to)
(defparameter segment-mask #x1E );; VG_SEGMENT_MASK
(export 'segment-mask)
;; (defparameter path-segment-force-size #x7FFFFFFF );; VG_PATH_SEGMENT_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:483:9)
;;
(defctype string-id xfixnum);; was _VGStringID
(export 'string-id)
(defparameter vendor #x2300 );; VG_VENDOR
(export 'vendor)
(defparameter renderer #x2301 );; VG_RENDERER
(export 'renderer)
(defparameter version #x2302 );; VG_VERSION
(export 'version)
(defparameter extensions #x2303 );; VG_EXTENSIONS
(export 'extensions)
;; (defparameter string-id-force-size #x7FFFFFFF );; VG_STRING_ID_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:739:42)
;;
(declaim (inline &get-string))
(defcfun ("vgGetString" &get-string) :string
  "see: (/opt/vc/include/VG/openvg.h:739:42)"
  (name  string-id) ;; name #<typedef VGStringID>
)
(export '&get-string)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:469:9)
;;
(defctype hardware-query-type xfixnum);; was _VGHardwareQueryType
(export 'hardware-query-type)
(defparameter image-format-query #x2100 );; VG_IMAGE_FORMAT_QUERY
(export 'image-format-query)
(defparameter path-datatype-query #x2101 );; VG_PATH_DATATYPE_QUERY
(export 'path-datatype-query)
;; (defparameter hardware-query-type-force-size #x7FFFFFFF );; VG_HARDWARE_QUERY_TYPE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:476:9)
;;
(defctype hardware-query-result xfixnum);; was _VGHardwareQueryResult
(export 'hardware-query-result)
(defparameter hardware-accelerated #x2200 );; VG_HARDWARE_ACCELERATED
(export 'hardware-accelerated)
(defparameter hardware-unaccelerated #x2201 );; VG_HARDWARE_UNACCELERATED
(export 'hardware-unaccelerated)
;; (defparameter hardware-query-result-force-size #x7FFFFFFF );; VG_HARDWARE_QUERY_RESULT_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:735:48)
;;
(declaim (inline &hardware-query))
(defcfun ("vgHardwareQuery" &hardware-query) hardware-query-result
  "see: (/opt/vc/include/VG/openvg.h:735:48)"
  (key  hardware-query-type) ;; key #<typedef VGHardwareQueryType>
  (setting  :INT) ;; setting #<typedef VGint>
)
(export '&hardware-query)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:439:9)
;;
(defctype image-channel xfixnum);; was _VGImageChannel
(export 'image-channel)
(defparameter red #x8 );; VG_RED
(export 'red)
(defparameter green #x4 );; VG_GREEN
(export 'green)
(defparameter blue #x2 );; VG_BLUE
(export 'blue)
(defparameter alpha #x1 );; VG_ALPHA
(export 'alpha)
;; (defparameter image-channel-force-size #x7FFFFFFF );; VG_IMAGE_CHANNEL_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:728:31)
;;
(declaim (inline &lookup-single))
(defcfun ("vgLookupSingle" &lookup-single) :VOID
  "see: (/opt/vc/include/VG/openvg.h:728:31)"
  (dst  :UINT) ;; dst #<typedef VGImage>
  (src  :UINT) ;; src #<typedef VGImage>
  (lookup-table  (:pointer :UINT)) ;; lookupTable #<POINTER #<typedef VGuint>>
  (source-channel  image-channel) ;; sourceChannel #<typedef VGImageChannel>
  (output-linear  XFIXNUM) ;; outputLinear #<typedef VGboolean>
  (output-premultiplied  XFIXNUM) ;; outputPremultiplied #<typedef VGboolean>
)
(export '&lookup-single)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:721:31)
;;
(declaim (inline &lookup))
(defcfun ("vgLookup" &lookup) :VOID
  "see: (/opt/vc/include/VG/openvg.h:721:31)"
  (dst  :UINT) ;; dst #<typedef VGImage>
  (src  :UINT) ;; src #<typedef VGImage>
  (red-lut  (:pointer :UCHAR)) ;; redLUT #<POINTER #<typedef VGubyte>>
  (green-lut  (:pointer :UCHAR)) ;; greenLUT #<POINTER #<typedef VGubyte>>
  (blue-lut  (:pointer :UCHAR)) ;; blueLUT #<POINTER #<typedef VGubyte>>
  (alpha-lut  (:pointer :UCHAR)) ;; alphaLUT #<POINTER #<typedef VGubyte>>
  (output-linear  XFIXNUM) ;; outputLinear #<typedef VGboolean>
  (output-premultiplied  XFIXNUM) ;; outputPremultiplied #<typedef VGboolean>
)
(export '&lookup)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:354:9)
;;
(defctype tiling-mode xfixnum);; was _VGTilingMode
(export 'tiling-mode)
(defparameter tile-fill #x1D00 );; VG_TILE_FILL
(export 'tile-fill)
(defparameter tile-pad #x1D01 );; VG_TILE_PAD
(export 'tile-pad)
(defparameter tile-repeat #x1D02 );; VG_TILE_REPEAT
(export 'tile-repeat)
(defparameter tile-reflect #x1D03 );; VG_TILE_REFLECT
(export 'tile-reflect)
;; (defparameter tiling-mode-force-size #x7FFFFFFF );; VG_TILING_MODE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:717:31)
;;
(declaim (inline &gaussian-blur))
(defcfun ("vgGaussianBlur" &gaussian-blur) :VOID
  "see: (/opt/vc/include/VG/openvg.h:717:31)"
  (dst  :UINT) ;; dst #<typedef VGImage>
  (src  :UINT) ;; src #<typedef VGImage>
  (std-deviation-x  :FLOAT) ;; stdDeviationX #<typedef VGfloat>
  (std-deviation-y  :FLOAT) ;; stdDeviationY #<typedef VGfloat>
  (tiling-mode  tiling-mode) ;; tilingMode #<typedef VGTilingMode>
)
(export '&gaussian-blur)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:708:31)
;;
(declaim (inline &separable-convolve))
(defcfun ("vgSeparableConvolve" &separable-convolve) :VOID
  "see: (/opt/vc/include/VG/openvg.h:708:31)"
  (dst  :UINT) ;; dst #<typedef VGImage>
  (src  :UINT) ;; src #<typedef VGImage>
  (kernel-width  :INT) ;; kernelWidth #<typedef VGint>
  (kernel-height  :INT) ;; kernelHeight #<typedef VGint>
  (shift-x  :INT) ;; shiftX #<typedef VGint>
  (shift-y  :INT) ;; shiftY #<typedef VGint>
  (kernel-x  (:pointer :SHORT)) ;; kernelX #<POINTER #<typedef VGshort>>
  (kernel-y  (:pointer :SHORT)) ;; kernelY #<POINTER #<typedef VGshort>>
  (scale  :FLOAT) ;; scale #<typedef VGfloat>
  (bias  :FLOAT) ;; bias #<typedef VGfloat>
  (tiling-mode  tiling-mode) ;; tilingMode #<typedef VGTilingMode>
)
(export '&separable-convolve)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:701:31)
;;
(declaim (inline &convolve))
(defcfun ("vgConvolve" &convolve) :VOID
  "see: (/opt/vc/include/VG/openvg.h:701:31)"
  (dst  :UINT) ;; dst #<typedef VGImage>
  (src  :UINT) ;; src #<typedef VGImage>
  (kernel-width  :INT) ;; kernelWidth #<typedef VGint>
  (kernel-height  :INT) ;; kernelHeight #<typedef VGint>
  (shift-x  :INT) ;; shiftX #<typedef VGint>
  (shift-y  :INT) ;; shiftY #<typedef VGint>
  (kernel  (:pointer :SHORT)) ;; kernel #<POINTER #<typedef VGshort>>
  (scale  :FLOAT) ;; scale #<typedef VGfloat>
  (bias  :FLOAT) ;; bias #<typedef VGfloat>
  (tiling-mode  tiling-mode) ;; tilingMode #<typedef VGTilingMode>
)
(export '&convolve)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:699:31)
;;
(declaim (inline &color-matrix))
(defcfun ("vgColorMatrix" &color-matrix) :VOID
  "see: (/opt/vc/include/VG/openvg.h:699:31)"
  (dst  :UINT) ;; dst #<typedef VGImage>
  (src  :UINT) ;; src #<typedef VGImage>
  (matrix  (:pointer :FLOAT)) ;; matrix #<POINTER #<typedef VGfloat>>
)
(export '&color-matrix)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:690:31)n
;;
(declaim (inline &draw-glyphs))
(defcfun ("vgDrawGlyphs" &draw-glyphs) :VOID
  "see: (/opt/vc/include/VG/openvg.h:690:31)"
  (font  :UINT) ;; font #<typedef VGFont>
  (glyph-count  :INT) ;; glyphCount #<typedef VGint>
  (glyph-indices  (:pointer :UINT)) ;; glyphIndices #<POINTER #<typedef VGuint>>
  (adjustments-x  (:pointer :FLOAT)) ;; adjustments_x #<POINTER #<typedef VGfloat>>
  (adjustments-y  (:pointer :FLOAT)) ;; adjustments_y #<POINTER #<typedef VGfloat>>
  (paint-modes XFIXNUM ) ;; paintModes #<typedef VGbitfield>
  (allow-auto-hinting  XFIXNUM) ;; allowAutoHinting #<typedef VGboolean>
)
(export '&draw-glyphs)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:686:31)
;;
(declaim (inline &draw-glyph))
(defcfun ("vgDrawGlyph" &draw-glyph) :VOID
  "see: (/opt/vc/include/VG/openvg.h:686:31)"
  (font  :UINT) ;; font #<typedef VGFont>
  (glyph-index  XFIXNUM) ;; glyphIndex #<typedef VGuint>
  (paint-modes  XFIXNUM) ;; paintModes #<typedef VGbitfield>
  (allow-auto-hinting XFIXNUM) ;; allowAutoHinting #<typedef VGboolean>
)
(export '&draw-glyph)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:685:31)
;;
(declaim (inline &clear-glyph))
(defcfun ("vgClearGlyph" &clear-glyph) :VOID
  "see: (/opt/vc/include/VG/openvg.h:685:31)"
  (font  :UINT) ;; font #<typedef VGFont>
  (glyph-index  XFIXNUM) ;; glyphIndex #<typedef VGuint>
)
(export '&clear-glyph)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:680:31)
;;
(declaim (inline &set-glyph-to-image))
(defcfun ("vgSetGlyphToImage" &set-glyph-to-image) :VOID
  "see: (/opt/vc/include/VG/openvg.h:680:31)"
  (font  :UINT) ;; font #<typedef VGFont>
  (glyph-index  XFIXNUM) ;; glyphIndex #<typedef VGuint>
  (image  :UINT) ;; image #<typedef VGImage>
  (glyph-origin  (:pointer :FLOAT )) ;; glyphOrigin #<array [2] of #<typedef VGfloat>>
  (escapement  (:pointer :FLOAT )) ;; escapement #<array [2] of #<typedef VGfloat>>
)
(export '&set-glyph-to-image)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:674:31)
;;
(declaim (inline &set-glyph-to-path))
(defcfun ("vgSetGlyphToPath" &set-glyph-to-path) :VOID
  "see: (/opt/vc/include/VG/openvg.h:674:31)"
  (font  :UINT) ;; font #<typedef VGFont>
  (glyph-index  XFIXNUM) ;; glyphIndex #<typedef VGuint>
  (path  :UINT) ;; path #<typedef VGPath>
  (is-hinted  XFIXNUM) ;; isHinted #<typedef VGboolean>
  (glyph-origin  (:pointer :FLOAT )) ;; glyphOrigin #<array [2] of #<typedef VGfloat>>
  (escapement  (:pointer :FLOAT )) ;; escapement #<array [2] of #<typedef VGfloat>>
)
(export '&set-glyph-to-path)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:673:31)
;;
(declaim (inline &destroy-font))
(defcfun ("vgDestroyFont" &destroy-font) :VOID
  "see: (/opt/vc/include/VG/openvg.h:673:31)"
  (font  :UINT) ;; font #<typedef VGFont>
)
(export '&destroy-font)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:672:33)
;;
(declaim (inline &create-font))
(defcfun ("vgCreateFont" &create-font) :UINT
  "see: (/opt/vc/include/VG/openvg.h:672:33)"
  (glyph-capacity-hint  :INT) ;; glyphCapacityHint #<typedef VGint>
)
(export '&create-font)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:667:31)
;;
(declaim (inline &copy-pixels))
(defcfun ("vgCopyPixels" &copy-pixels) :VOID
  "see: (/opt/vc/include/VG/openvg.h:667:31)"
  (dx  XFIXNUM) ;; dx #<typedef VGint>
  (dy  XFIXNUM) ;; dy #<typedef VGint>
  (sx  XFIXNUM) ;; sx #<typedef VGint>
  (sy  XFIXNUM) ;; sy #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&copy-pixels)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:363:9)
;;
(defctype image-format xfixnum);; was _VGImageFormat
(export 'image-format)
(defparameter s-rgbx-8888 #x0 );; VG_sRGBX_8888
(export 's-rgbx-8888)
(defparameter s-rgba-8888 #x1 );; VG_sRGBA_8888
(export 's-rgba-8888)
(defparameter s-rgba-8888-pre #x2 );; VG_sRGBA_8888_PRE
(export 's-rgba-8888-pre)
(defparameter s-rgb-565 #x3 );; VG_sRGB_565
(export 's-rgb-565)
(defparameter s-rgba-5551 #x4 );; VG_sRGBA_5551
(export 's-rgba-5551)
(defparameter s-rgba-4444 #x5 );; VG_sRGBA_4444
(export 's-rgba-4444)
(defparameter s-l-8 #x6 );; VG_sL_8
(export 's-l-8)
(defparameter l-rgbx-8888 #x7 );; VG_lRGBX_8888
(export 'l-rgbx-8888)
(defparameter l-rgba-8888 #x8 );; VG_lRGBA_8888
(export 'l-rgba-8888)
(defparameter l-rgba-8888-pre #x9 );; VG_lRGBA_8888_PRE
(export 'l-rgba-8888-pre)
(defparameter l-l-8 #xA );; VG_lL_8
(export 'l-l-8)
(defparameter a-8 #xB );; VG_A_8
(export 'a-8)
(defparameter bw-1 #xC );; VG_BW_1
(export 'bw-1)
(defparameter a-1 #xD );; VG_A_1
(export 'a-1)
(defparameter a-4 #xE );; VG_A_4
(export 'a-4)
(defparameter s-xrgb-8888 #x40 );; VG_sXRGB_8888
(export 's-xrgb-8888)
(defparameter s-argb-8888 #x41 );; VG_sARGB_8888
(export 's-argb-8888)
(defparameter s-argb-8888-pre #x42 );; VG_sARGB_8888_PRE
(export 's-argb-8888-pre)
(defparameter s-argb-1555 #x44 );; VG_sARGB_1555
(export 's-argb-1555)
(defparameter s-argb-4444 #x45 );; VG_sARGB_4444
(export 's-argb-4444)
(defparameter l-xrgb-8888 #x47 );; VG_lXRGB_8888
(export 'l-xrgb-8888)
(defparameter l-argb-8888 #x48 );; VG_lARGB_8888
(export 'l-argb-8888)
(defparameter l-argb-8888-pre #x49 );; VG_lARGB_8888_PRE
(export 'l-argb-8888-pre)
(defparameter s-bgrx-8888 #x80 );; VG_sBGRX_8888
(export 's-bgrx-8888)
(defparameter s-bgra-8888 #x81 );; VG_sBGRA_8888
(export 's-bgra-8888)
(defparameter s-bgra-8888-pre #x82 );; VG_sBGRA_8888_PRE
(export 's-bgra-8888-pre)
(defparameter s-bgr-565 #x83 );; VG_sBGR_565
(export 's-bgr-565)
(defparameter s-bgra-5551 #x84 );; VG_sBGRA_5551
(export 's-bgra-5551)
(defparameter s-bgra-4444 #x85 );; VG_sBGRA_4444
(export 's-bgra-4444)
(defparameter l-bgrx-8888 #x87 );; VG_lBGRX_8888
(export 'l-bgrx-8888)
(defparameter l-bgra-8888 #x88 );; VG_lBGRA_8888
(export 'l-bgra-8888)
(defparameter l-bgra-8888-pre #x89 );; VG_lBGRA_8888_PRE
(export 'l-bgra-8888-pre)
(defparameter s-xbgr-8888 #xC0 );; VG_sXBGR_8888
(export 's-xbgr-8888)
(defparameter s-abgr-8888 #xC1 );; VG_sABGR_8888
(export 's-abgr-8888)
(defparameter s-abgr-8888-pre #xC2 );; VG_sABGR_8888_PRE
(export 's-abgr-8888-pre)
(defparameter s-abgr-1555 #xC4 );; VG_sABGR_1555
(export 's-abgr-1555)
(defparameter s-abgr-4444 #xC5 );; VG_sABGR_4444
(export 's-abgr-4444)
(defparameter l-xbgr-8888 #xC7 );; VG_lXBGR_8888
(export 'l-xbgr-8888)
(defparameter l-abgr-8888 #xC8 );; VG_lABGR_8888
(export 'l-abgr-8888)
(defparameter l-abgr-8888-pre #xC9 );; VG_lABGR_8888_PRE
(export 'l-abgr-8888-pre)
;; (defparameter image-format-force-size #x7FFFFFFF );; VG_IMAGE_FORMAT_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:663:31)
;;
(declaim (inline &read-pixels))
(defcfun ("vgReadPixels" &read-pixels) :VOID
  "see: (/opt/vc/include/VG/openvg.h:663:31)"
  (data  (:pointer :VOID)) ;; data #<POINTER #<VBASE :void>>
  (data-stride  XFIXNUM) ;; dataStride #<typedef VGint>
  (data-format  image-format) ;; dataFormat #<typedef VGImageFormat>
  (sx  XFIXNUM) ;; sx #<typedef VGint>
  (sy  XFIXNUM) ;; sy #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&read-pixels)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:660:31)
;;
(declaim (inline &get-pixels))
(defcfun ("vgGetPixels" &get-pixels) :VOID
  "see: (/opt/vc/include/VG/openvg.h:660:31)"
  (dst  :UINT) ;; dst #<typedef VGImage>
  (dx  XFIXNUM) ;; dx #<typedef VGint>
  (dy  XFIXNUM) ;; dy #<typedef VGint>
  (sx  XFIXNUM) ;; sx #<typedef VGint>
  (sy  XFIXNUM) ;; sy #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&get-pixels)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:656:31)
;;
(declaim (inline &write-pixels))
(defcfun ("vgWritePixels" &write-pixels) :VOID
  "see: (/opt/vc/include/VG/openvg.h:656:31)"
  (data  (:pointer :VOID)) ;; data #<POINTER #<VBASE :void>>
  (data-stride  XFIXNUM) ;; dataStride #<typedef VGint>
  (data-format  image-format) ;; dataFormat #<typedef VGImageFormat>
  (dx  XFIXNUM) ;; dx #<typedef VGint>
  (dy  XFIXNUM) ;; dy #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&write-pixels)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:653:31)
;;
(declaim (inline &set-pixels))
(defcfun ("vgSetPixels" &set-pixels) :VOID
  "see: (/opt/vc/include/VG/openvg.h:653:31)"
  (dx  XFIXNUM) ;; dx #<typedef VGint>
  (dy  XFIXNUM) ;; dy #<typedef VGint>
  (src  :UINT) ;; src #<typedef VGImage>
  (sx  XFIXNUM) ;; sx #<typedef VGint>
  (sy  XFIXNUM) ;; sy #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&set-pixels)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:652:31)
;;
(declaim (inline &draw-image))
(defcfun ("vgDrawImage" &draw-image) :VOID
  "see: (/opt/vc/include/VG/openvg.h:652:31)"
  (image  :UINT) ;; image #<typedef VGImage>
)
(export '&draw-image)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:648:31)
;;
(declaim (inline &copy-image))
(defcfun ("vgCopyImage" &copy-image) :VOID
  "see: (/opt/vc/include/VG/openvg.h:648:31)"
  (dst  :UINT) ;; dst #<typedef VGImage>
  (dx  XFIXNUM) ;; dx #<typedef VGint>
  (dy  XFIXNUM)  ;; dy #<typedef VGint>
  (src :UINT) ;; src #<typedef VGImage>
  (sx  XFIXNUM) ;; sx #<typedef VGint>
  (sy  XFIXNUM) ;; sy #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
  (dither  XFIXNUM) ;; dither #<typedef VGboolean>
)
(export '&copy-image)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:647:34)
;;
(declaim (inline &get-parent))
(defcfun ("vgGetParent" &get-parent) :UINT
  "see: (/opt/vc/include/VG/openvg.h:647:34)"
  (image  :UINT) ;; image #<typedef VGImage>
)
(export '&get-parent)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:645:34)
;;
(declaim (inline &child-image))
(defcfun ("vgChildImage" &child-image) :UINT
  "see: (/opt/vc/include/VG/openvg.h:645:34)"
  (parent  :UINT) ;; parent #<typedef VGImage>
  (x  XFIXNUM) ;; x #<typedef VGint>
  (y  XFIXNUM) ;; y #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&child-image)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:640:31)
;;
(declaim (inline &get-image-sub-data))
(defcfun ("vgGetImageSubData" &get-image-sub-data) :VOID
  "see: (/opt/vc/include/VG/openvg.h:640:31)"
  (image  :UINT) ;; image #<typedef VGImage>
  (data  (:pointer :VOID)) ;; data #<POINTER #<VBASE :void>>
  (data-stride  XFIXNUM) ;; dataStride #<typedef VGint>
  (data-format  image-format) ;; dataFormat #<typedef VGImageFormat>
  (x  XFIXNUM) ;; x #<typedef VGint>
  (y  XFIXNUM) ;; y #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&get-image-sub-data)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:636:31)
;;
(declaim (inline &image-sub-data))
(defcfun ("vgImageSubData" &image-sub-data) :VOID
  "see: (/opt/vc/include/VG/openvg.h:636:31)"
  (image  :UINT) ;; image #<typedef VGImage>
  (data  (:pointer :VOID)) ;; data #<POINTER #<VBASE :void>>
  (data-stride  XFIXNUM) ;; dataStride #<typedef VGint>
  (data-format  image-format) ;; dataFormat #<typedef VGImageFormat>
  (x  XFIXNUM) ;; x #<typedef VGint>
  (y  XFIXNUM) ;; y #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&image-sub-data)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:634:31)
;;
(declaim (inline &clear-image))
(defcfun ("vgClearImage" &clear-image) :VOID
  "see: (/opt/vc/include/VG/openvg.h:634:31)"
  (image  :UINT) ;; image #<typedef VGImage>
  (x  XFIXNUM) ;; x #<typedef VGint>
  (y  XFIXNUM) ;; y #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&clear-image)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:633:31)
;;
(declaim (inline &destroy-image))
(defcfun ("vgDestroyImage" &destroy-image) :VOID
  "see: (/opt/vc/include/VG/openvg.h:633:31)"
  (image  :UINT) ;; image #<typedef VGImage>
)
(export '&destroy-image)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:630:34)
;;
(declaim (inline &create-image))
(defcfun ("vgCreateImage" &create-image) :UINT
  "see: (/opt/vc/include/VG/openvg.h:630:34)"
  (format  image-format) ;; format #<typedef VGImageFormat>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
  (allowed-quality  XFIXNUM) ;; allowedQuality #<typedef VGbitfield>
)
(export '&create-image)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:627:31)
;;
(declaim (inline &paint-pattern))
(defcfun ("vgPaintPattern" &paint-pattern) :VOID
  "see: (/opt/vc/include/VG/openvg.h:627:31)"
  (paint  :UINT) ;; paint #<typedef VGPaint>
  (pattern  :UINT) ;; pattern #<typedef VGImage>
)
(export '&paint-pattern)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:626:33)
;;
(declaim (inline &get-color))
(defcfun ("vgGetColor" &get-color) :UINT
  "see: (/opt/vc/include/VG/openvg.h:626:33)"
  (paint  :UINT) ;; paint #<typedef VGPaint>
)
(export '&get-color)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:625:31)
;;
(declaim (inline &set-color))
(defcfun ("vgSetColor" &set-color) :VOID
  "see: (/opt/vc/include/VG/openvg.h:625:31)"
  (paint  :UINT) ;; paint #<typedef VGPaint>
  (rgba  :UINT) ;; rgba #<typedef VGuint>
)
(export '&set-color)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:310:9)
;;
(defctype paint-mode xfixnum);; was _VGPaintMode
(export 'paint-mode)
(defparameter stroke-path #x1 );; VG_STROKE_PATH
(export 'stroke-path)
(defparameter fill-path #x2 );; VG_FILL_PATH
(export 'fill-path)
;; (defparameter paint-mode-force-size #x7FFFFFFF );; VG_PAINT_MODE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:624:34)
;;
(declaim (inline &get-paint))
(defcfun ("vgGetPaint" &get-paint) :UINT
  "see: (/opt/vc/include/VG/openvg.h:624:34)"
  (paint-mode  paint-mode) ;; paintMode #<typedef VGPaintMode>
)
(export '&get-paint)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:623:31)
;;
(declaim (inline &set-paint))
(defcfun ("vgSetPaint" &set-paint) :VOID
  "see: (/opt/vc/include/VG/openvg.h:623:31)"
  (paint  :UINT) ;; paint #<typedef VGPaint>
  (paint-modes  :UINT) ;; paintModes #<typedef VGbitfield>
)
(export '&set-paint)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:622:31)
;;
(declaim (inline &destroy-paint))
(defcfun ("vgDestroyPaint" &destroy-paint) :VOID
  "see: (/opt/vc/include/VG/openvg.h:622:31)"
  (paint  :UINT) ;; paint #<typedef VGPaint>
)
(export '&destroy-paint)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:621:34)
;;
(declaim (inline &create-paint))
(declaim (ftype (function () (unsigned-byte 32)) &create-paint))
(defcfun ("vgCreatePaint" &create-paint) :UINT
  "see: (/opt/vc/include/VG/openvg.h:621:34)"
)
(export '&create-paint)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:618:31)
;;
(declaim (inline &draw-path))
(defcfun ("vgDrawPath" &draw-path) :VOID
  "see: (/opt/vc/include/VG/openvg.h:618:31)"
  (path  :UINT) ;; path #<typedef VGPath>
  (paint-modes  XFIXNUM) ;; paintModes #<typedef VGbitfield>
)
(export '&draw-path)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:615:31)
;;
(declaim (inline &path-transformed-bounds))
(defcfun ("vgPathTransformedBounds" &path-transformed-bounds) :VOID
  "see: (/opt/vc/include/VG/openvg.h:615:31)"
  (path  :UINT) ;; path #<typedef VGPath>
  (min-x  (:pointer :FLOAT)) ;; minX #<POINTER #<typedef VGfloat>>
  (min-y  (:pointer :FLOAT)) ;; minY #<POINTER #<typedef VGfloat>>
  (width  (:pointer :FLOAT)) ;; width #<POINTER #<typedef VGfloat>>
  (height  (:pointer :FLOAT)) ;; height #<POINTER #<typedef VGfloat>>
)
(export '&path-transformed-bounds)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:612:31)
;;
(declaim (inline &path-bounds))
(defcfun ("vgPathBounds" &path-bounds) :VOID
  "see: (/opt/vc/include/VG/openvg.h:612:31)"
  (path  :UINT) ;; path #<typedef VGPath>
  (min-x  (:pointer :FLOAT)) ;; minX #<POINTER #<typedef VGfloat>>
  (min-y  (:pointer :FLOAT)) ;; minY #<POINTER #<typedef VGfloat>>
  (width  (:pointer :FLOAT)) ;; width #<POINTER #<typedef VGfloat>>
  (height  (:pointer :FLOAT)) ;; height #<POINTER #<typedef VGfloat>>
)
(export '&path-bounds)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:607:31)
;;
(declaim (inline &point-along-path))
(defcfun ("vgPointAlongPath" &point-along-path) :VOID
  "see: (/opt/vc/include/VG/openvg.h:607:31)"
  (path  :UINT) ;; path #<typedef VGPath>
  (start-segment  XFIXNUM) ;; startSegment #<typedef VGint>
  (num-segments  XFIXNUM) ;; numSegments #<typedef VGint>
  (distance  :FLOAT) ;; distance #<typedef VGfloat>
  (x  (:pointer :FLOAT)) ;; x #<POINTER #<typedef VGfloat>>
  (y  (:pointer :FLOAT)) ;; y #<POINTER #<typedef VGfloat>>
  (tangent-x  (:pointer :FLOAT)) ;; tangentX #<POINTER #<typedef VGfloat>>
  (tangent-y  (:pointer :FLOAT)) ;; tangentY #<POINTER #<typedef VGfloat>>
)
(export '&point-along-path)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:605:34)
;;
(declaim (inline &path-length))
(defcfun ("vgPathLength" &path-length) :FLOAT
  "see: (/opt/vc/include/VG/openvg.h:605:34)"
  (path  :UINT) ;; path #<typedef VGPath>
  (start-segment  XFIXNUM) ;; startSegment #<typedef VGint>
  (num-segments  XFIXNUM) ;; numSegments #<typedef VGint>
)
(export '&path-length)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:601:36)
;;
(declaim (inline &interpolate-path))
(defcfun ("vgInterpolatePath" &interpolate-path) :UINT
  "see: (/opt/vc/include/VG/openvg.h:601:36)"
  (dst-path  :UINT) ;; dstPath #<typedef VGPath>
  (start-path  :UINT) ;; startPath #<typedef VGPath>
  (end-path  :UINT) ;; endPath #<typedef VGPath>
  (amount  :FLOAT) ;; amount #<typedef VGfloat>
)
(export '&interpolate-path)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:600:31)
;;
(declaim (inline &transform-path))
(defcfun ("vgTransformPath" &transform-path) :VOID
  "see: (/opt/vc/include/VG/openvg.h:600:31)"
  (dst-path  :UINT) ;; dstPath #<typedef VGPath>
  (src-path  :UINT) ;; srcPath #<typedef VGPath>
)
(export '&transform-path)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:597:31)
;;
(declaim (inline &modify-path-coords))
(defcfun ("vgModifyPathCoords" &modify-path-coords) :VOID
  "see: (/opt/vc/include/VG/openvg.h:597:31)"
  (dst-path  :UINT) ;; dstPath #<typedef VGPath>
  (start-index  XFIXNUM) ;; startIndex #<typedef VGint>
  (num-segments  XFIXNUM) ;; numSegments #<typedef VGint>
  (path-data  (:pointer :VOID)) ;; pathData #<POINTER #<VBASE :void>>
)
(export '&modify-path-coords)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:593:31)
;;
(declaim (inline &append-path-data))
(defcfun ("vgAppendPathData" &append-path-data) :VOID
  "see: (/opt/vc/include/VG/openvg.h:593:31)"
  (dst-path  :UINT) ;; dstPath #<typedef VGPath>
  (num-segments  XFIXNUM) ;; numSegments #<typedef VGint>
  (path-segments  (:pointer :UCHAR)) ;; pathSegments #<POINTER #<typedef VGubyte>>
  (path-data  (:pointer :VOID)) ;; pathData #<POINTER #<VBASE :void>>
)
(export '&append-path-data)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:592:31)
;;
(declaim (inline &append-path))
(defcfun ("vgAppendPath" &append-path) :VOID
  "see: (/opt/vc/include/VG/openvg.h:592:31)"
  (dst-path  :UINT) ;; dstPath #<typedef VGPath>
  (src-path  :UINT) ;; srcPath #<typedef VGPath>
)
(export '&append-path)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:591:37)
;;
(declaim (inline &get-path-capabilities))
(defcfun ("vgGetPathCapabilities" &get-path-capabilities) :UINT
  "see: (/opt/vc/include/VG/openvg.h:591:37)"
  (path  :UINT) ;; path #<typedef VGPath>
)
(export '&get-path-capabilities)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:589:31)
;;
(declaim (inline &remove-path-capabilities))
(defcfun ("vgRemovePathCapabilities" &remove-path-capabilities) :VOID
  "see: (/opt/vc/include/VG/openvg.h:589:31)"
  (path  :UINT) ;; path #<typedef VGPath>
  (capabilities  :UINT) ;; capabilities #<typedef VGbitfield>
)
(export '&remove-path-capabilities)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:588:31)
;;
(declaim (inline &destroy-path))
(defcfun ("vgDestroyPath" &destroy-path) :VOID
  "see: (/opt/vc/include/VG/openvg.h:588:31)"
  (path  :UINT) ;; path #<typedef VGPath>
)
(export '&destroy-path)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:587:31)
;;
(declaim (inline &clear-path))
(defcfun ("vgClearPath" &clear-path) :VOID
  "see: (/opt/vc/include/VG/openvg.h:587:31)"
  (path  :UINT) ;; path #<typedef VGPath>
  (capabilities  :UINT) ;; capabilities #<typedef VGbitfield>
)
(export '&clear-path)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:193:9)
;;
(defctype path-datatype xfixnum);; was _VGPathDatatype
(export 'path-datatype)
(defparameter path-datatype-s-8 #x0 );; VG_PATH_DATATYPE_S_8
(export 'path-datatype-s-8)
(defparameter path-datatype-s-16 #x1 );; VG_PATH_DATATYPE_S_16
(export 'path-datatype-s-16)
(defparameter path-datatype-s-32 #x2 );; VG_PATH_DATATYPE_S_32
(export 'path-datatype-s-32)
(defparameter path-datatype-f #x3 );; VG_PATH_DATATYPE_F
(export 'path-datatype-f)
;; (defparameter path-datatype-force-size #x7FFFFFFF );; VG_PATH_DATATYPE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:581:33)
;;*
(declaim (inline &create-path))
(defcfun ("vgCreatePath" &create-path) :UINT
  "see: (/opt/vc/include/VG/openvg.h:581:33)"
  (path-format  XFIXNUM) ;; pathFormat #<typedef VGint>
  (datatype  path-datatype) ;; datatype #<typedef VGPathDatatype>
  (scale  :FLOAT) ;; scale #<typedef VGfloat>
  (bias  :FLOAT) ;; bias #<typedef VGfloat>
  (segment-capacity-hint  XFIXNUM) ;; segmentCapacityHint #<typedef VGint>
  (coord-capacity-hint  XFIXNUM) ;; coordCapacityHint #<typedef VGint>
  (capabilities  XFIXNUM) ;; capabilities #<typedef VGbitfield>
)
(export '&create-path)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:578:31)
;;
(declaim (inline &clear))
(defcfun ("vgClear" &clear) :VOID
  "see: (/opt/vc/include/VG/openvg.h:578:31)"
  (x  XFIXNUM) ;; x #<typedef VGint>
  (y  XFIXNUM) ;; y #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&clear)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:574:31)
;;
(declaim (inline &copy-mask))
(defcfun ("vgCopyMask" &copy-mask) :VOID
  "see: (/opt/vc/include/VG/openvg.h:574:31)"
  (mask-layer  :UINT) ;; maskLayer #<typedef VGMaskLayer>
  (dx  XFIXNUM) ;; dx #<typedef VGint>
  (dy  XFIXNUM) ;; dy #<typedef VGint>
  (sx  XFIXNUM) ;; sx #<typedef VGint>
  (sy  XFIXNUM) ;; sy #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&copy-mask)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:570:31)
;;
(declaim (inline &fill-mask-layer))
(defcfun ("vgFillMaskLayer" &fill-mask-layer) :VOID
  "see: (/opt/vc/include/VG/openvg.h:570:31)"
  (mask-layer  :UINT) ;; maskLayer #<typedef VGMaskLayer>
  (x  XFIXNUM) ;; x #<typedef VGint>
  (y  XFIXNUM) ;; y #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
  (value  :FLOAT) ;; value #<typedef VGfloat>
)
(export '&fill-mask-layer)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:569:31)
;;
(declaim (inline &destroy-mask-layer))
(defcfun ("vgDestroyMaskLayer" &destroy-mask-layer) :VOID
  "see: (/opt/vc/include/VG/openvg.h:569:31)"
  (mask-layer  :UINT) ;; maskLayer #<typedef VGMaskLayer>
)
(export '&destroy-mask-layer)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:568:38)
;;
(declaim (inline &create-mask-layer))
(defcfun ("vgCreateMaskLayer" &create-mask-layer) :UINT
  "see: (/opt/vc/include/VG/openvg.h:568:38)"
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&create-mask-layer)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:180:9)
;;
(defctype mask-operation xfixnum);; was _VGMaskOperation
(export 'mask-operation)
(defparameter clear-mask #x1500 );; VG_CLEAR_MASK
(export 'clear-mask)
(defparameter fill-mask #x1501 );; VG_FILL_MASK
(export 'fill-mask)
(defparameter set-mask #x1502 );; VG_SET_MASK
(export 'set-mask)
(defparameter union-mask #x1503 );; VG_UNION_MASK
(export 'union-mask)
(defparameter intersect-mask #x1504 );; VG_INTERSECT_MASK
(export 'intersect-mask)
(defparameter subtract-mask #x1505 );; VG_SUBTRACT_MASK
(export 'subtract-mask)
;; (defparameter mask-operation-force-size #x7FFFFFFF );; VG_MASK_OPERATION_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:565:31)
;;
(declaim (inline &render-to-mask))
(defcfun ("vgRenderToMask" &render-to-mask) :VOID
  "see: (/opt/vc/include/VG/openvg.h:565:31)"
  (path  :UINT) ;; path #<typedef VGPath>
  (paint-modes  :UINT) ;; paintModes #<typedef VGbitfield>
  (operation  mask-operation) ;; operation #<typedef VGMaskOperation>
)
(export '&render-to-mask)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:562:31)
;;
(declaim (inline &mask))
(defcfun ("vgMask" &mask) :VOID
  "see: (/opt/vc/include/VG/openvg.h:562:31)"
  (mask  :UINT) ;; mask #<typedef VGHandle>
  (operation  mask-operation) ;; operation #<typedef VGMaskOperation>
  (x  XFIXNUM) ;; x #<typedef VGint>
  (y  XFIXNUM) ;; y #<typedef VGint>
  (width  XFIXNUM) ;; width #<typedef VGint>
  (height  XFIXNUM) ;; height #<typedef VGint>
)
(export '&mask)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:559:31)
;;
(declaim (inline &rotate))
(defcfun ("vgRotate" &rotate) :VOID
  "see: (/opt/vc/include/VG/openvg.h:559:31)"
  (angle  :FLOAT) ;; angle #<typedef VGfloat>
)
(export '&rotate)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:558:31)
;;
(declaim (inline &shear))
(defcfun ("vgShear" &shear) :VOID
  "see: (/opt/vc/include/VG/openvg.h:558:31)"
  (shx  :FLOAT) ;; shx #<typedef VGfloat>
  (shy  :FLOAT) ;; shy #<typedef VGfloat>
)
(export '&shear)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:557:31)
;;
(declaim (inline &scale))
(defcfun ("vgScale" &scale) :VOID
  "see: (/opt/vc/include/VG/openvg.h:557:31)"
  (sx  :FLOAT) ;; sx #<typedef VGfloat>
  (sy  :FLOAT) ;; sy #<typedef VGfloat>
)
(export '&scale)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:556:31)
;;
(declaim (inline &translate))
(defcfun ("vgTranslate" &translate) :VOID
  "see: (/opt/vc/include/VG/openvg.h:556:31)"
  (tx  :FLOAT) ;; tx #<typedef VGfloat>
  (ty  :FLOAT) ;; ty #<typedef VGfloat>
)
(export '&translate)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:555:31)
;;
(declaim (inline &mult-matrix))
(defcfun ("vgMultMatrix" &mult-matrix) :VOID
  "see: (/opt/vc/include/VG/openvg.h:555:31)"
  (m  (:pointer :FLOAT)) ;; m #<POINTER #<typedef VGfloat>>
)
(export '&mult-matrix)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:554:31)
;;
(declaim (inline &get-matrix))
(defcfun ("vgGetMatrix" &get-matrix) :VOID
  "see: (/opt/vc/include/VG/openvg.h:554:31)"
  (m  (:pointer :FLOAT)) ;; m #<POINTER #<typedef VGfloat>>
)
(export '&get-matrix)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:553:31)
;;
(declaim (inline &load-matrix))
(defcfun ("vgLoadMatrix" &load-matrix) :VOID
  "see: (/opt/vc/include/VG/openvg.h:553:31)"
  (m  (:pointer :FLOAT)) ;; m #<POINTER #<typedef VGfloat>>
)
(export '&load-matrix)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:552:31)
;;
(declaim (inline &load-identity))
(defcfun ("vgLoadIdentity" &load-identity) :VOID
  "see: (/opt/vc/include/VG/openvg.h:552:31)"
)
(export '&load-identity)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:547:31)
;;
(declaim (inline &get-parameter-iv))
(defcfun ("vgGetParameteriv" &get-parameter-iv) :VOID
  "see: (/opt/vc/include/VG/openvg.h:547:31)"
  (object  :UINT) ;; object #<typedef VGHandle>
  (param-type  XFIXNUM) ;; paramType #<typedef VGint>
  (count  XFIXNUM) ;; count #<typedef VGint>
  (values  (:pointer :INT)) ;; values #<POINTER #<typedef VGint>>
)
(export '&get-parameter-iv)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:544:31)
;;
(declaim (inline &get-parameter-fv))
(defcfun ("vgGetParameterfv" &get-parameter-fv) :VOID
  "see: (/opt/vc/include/VG/openvg.h:544:31)"
  (object  :UINT) ;; object #<typedef VGHandle>
  (param-type  XFIXNUM) ;; paramType #<typedef VGint>
  (count  XFIXNUM) ;; count #<typedef VGint>
  (values  (:pointer :FLOAT)) ;; values #<POINTER #<typedef VGfloat>>
)
(export '&get-parameter-fv)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:542:32)
;;
(declaim (inline &get-parameter-vector-size))
(defcfun ("vgGetParameterVectorSize" &get-parameter-vector-size) :INT
  "see: (/opt/vc/include/VG/openvg.h:542:32)"
  (object  :UINT) ;; object #<typedef VGHandle>
  (param-type  XFIXNUM) ;; paramType #<typedef VGint>
)
(export '&get-parameter-vector-size)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:540:32)
;;
(declaim (inline &get-parameter-i))
(defcfun ("vgGetParameteri" &get-parameter-i) :INT
  "see: (/opt/vc/include/VG/openvg.h:540:32)"
  (object  :UINT) ;; object #<typedef VGHandle>
  (param-type  XFIXNUM) ;; paramType #<typedef VGint>
)
(export '&get-parameter-i)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:538:34)
;;
(declaim (inline &get-parameter-f))
(defcfun ("vgGetParameterf" &get-parameter-f) :FLOAT
  "see: (/opt/vc/include/VG/openvg.h:538:34)"
  (object  :UINT) ;; object #<typedef VGHandle>
  (param-type  XFIXNUM) ;; paramType #<typedef VGint>
)
(export '&get-parameter-f)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:534:31)
;;
(declaim (inline &set-parameter-iv))
(defcfun ("vgSetParameteriv" &set-parameter-iv) :VOID
  "see: (/opt/vc/include/VG/openvg.h:534:31)"
  (object  :UINT) ;; object #<typedef VGHandle>
  (param-type  XFIXNUM) ;; paramType #<typedef VGint>
  (count  XFIXNUM) ;; count #<typedef VGint>
  (values  (:pointer :INT)) ;; values #<POINTER #<typedef VGint>>
)
(export '&set-parameter-iv)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:531:31)
;;
(declaim (inline &set-parameter-fv))
(defcfun ("vgSetParameterfv" &set-parameter-fv) :VOID
  "see: (/opt/vc/include/VG/openvg.h:531:31)"
  (object  :UINT) ;; object #<typedef VGHandle>
  (param-type  XFIXNUM) ;; paramType #<typedef VGint>
  (count  XFIXNUM) ;; count #<typedef VGint>
  (values  (:pointer :FLOAT)) ;; values #<POINTER #<typedef VGfloat>>
)
(export '&set-parameter-fv)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:528:31)
;;
(declaim (inline &set-parameter-i))
(defcfun ("vgSetParameteri" &set-parameter-i) :VOID
  "see: (/opt/vc/include/VG/openvg.h:528:31)"
  (object  :UINT) ;; object #<typedef VGHandle>
  (param-type  XFIXNUM) ;; paramType #<typedef VGint>
  (value  :INT) ;; value #<typedef VGint>
)
(export '&set-parameter-i)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:525:31)
;;
(declaim (inline &set-parameter-f))
(defcfun ("vgSetParameterf" &set-parameter-f) :VOID
  "see: (/opt/vc/include/VG/openvg.h:525:31)"
  (object  :UINT) ;; object #<typedef VGHandle>
  (param-type  XFIXNUM) ;; paramType #<typedef VGint>
  (value  :FLOAT) ;; value #<typedef VGfloat>
)
(export '&set-parameter-f)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:87:9)
;;
(defctype param-type xfixnum);; was _VGParamType
(export 'param-type)
(defparameter matrix-mode #x1100 );; VG_MATRIX_MODE
(export 'matrix-mode)
(defparameter fill-rule #x1101 );; VG_FILL_RULE
(export 'fill-rule)
(defparameter image-quality #x1102 );; VG_IMAGE_QUALITY
(export 'image-quality)
(defparameter rendering-quality #x1103 );; VG_RENDERING_QUALITY
(export 'rendering-quality)
(defparameter blend-mode #x1104 );; VG_BLEND_MODE
(export 'blend-mode)
(defparameter image-mode #x1105 );; VG_IMAGE_MODE
(export 'image-mode)
(defparameter scissor-rects #x1106 );; VG_SCISSOR_RECTS
(export 'scissor-rects)
(defparameter color-transform #x1170 );; VG_COLOR_TRANSFORM
(export 'color-transform)
(defparameter color-transform-values #x1171 );; VG_COLOR_TRANSFORM_VALUES
(export 'color-transform-values)
(defparameter stroke-line-width #x1110 );; VG_STROKE_LINE_WIDTH
(export 'stroke-line-width)
(defparameter stroke-cap-style #x1111 );; VG_STROKE_CAP_STYLE
(export 'stroke-cap-style)
(defparameter stroke-join-style #x1112 );; VG_STROKE_JOIN_STYLE
(export 'stroke-join-style)
(defparameter stroke-miter-limit #x1113 );; VG_STROKE_MITER_LIMIT
(export 'stroke-miter-limit)
(defparameter stroke-dash-pattern #x1114 );; VG_STROKE_DASH_PATTERN
(export 'stroke-dash-pattern)
(defparameter stroke-dash-phase #x1115 );; VG_STROKE_DASH_PHASE
(export 'stroke-dash-phase)
(defparameter stroke-dash-phase-reset #x1116 );; VG_STROKE_DASH_PHASE_RESET
(export 'stroke-dash-phase-reset)
(defparameter tile-fill-color #x1120 );; VG_TILE_FILL_COLOR
(export 'tile-fill-color)
(defparameter clear-color #x1121 );; VG_CLEAR_COLOR
(export 'clear-color)
(defparameter glyph-origin #x1122 );; VG_GLYPH_ORIGIN
(export 'glyph-origin)
(defparameter masking #x1130 );; VG_MASKING
(export 'masking)
(defparameter scissoring #x1131 );; VG_SCISSORING
(export 'scissoring)
(defparameter pixel-layout #x1140 );; VG_PIXEL_LAYOUT
(export 'pixel-layout)
(defparameter screen-layout #x1141 );; VG_SCREEN_LAYOUT
(export 'screen-layout)
(defparameter filter-format-linear #x1150 );; VG_FILTER_FORMAT_LINEAR
(export 'filter-format-linear)
(defparameter filter-format-premultiplied #x1151 );; VG_FILTER_FORMAT_PREMULTIPLIED
(export 'filter-format-premultiplied)
(defparameter filter-channel-mask #x1152 );; VG_FILTER_CHANNEL_MASK
(export 'filter-channel-mask)
(defparameter max-scissor-rects #x1160 );; VG_MAX_SCISSOR_RECTS
(export 'max-scissor-rects)
(defparameter max-dash-count #x1161 );; VG_MAX_DASH_COUNT
(export 'max-dash-count)
(defparameter max-kernel-size #x1162 );; VG_MAX_KERNEL_SIZE
(export 'max-kernel-size)
(defparameter max-separable-kernel-size #x1163 );; VG_MAX_SEPARABLE_KERNEL_SIZE
(export 'max-separable-kernel-size)
(defparameter max-color-ramp-stops #x1164 );; VG_MAX_COLOR_RAMP_STOPS
(export 'max-color-ramp-stops)
(defparameter max-image-width #x1165 );; VG_MAX_IMAGE_WIDTH
(export 'max-image-width)
(defparameter max-image-height #x1166 );; VG_MAX_IMAGE_HEIGHT
(export 'max-image-height)
(defparameter max-image-pixels #x1167 );; VG_MAX_IMAGE_PIXELS
(export 'max-image-pixels)
(defparameter max-image-bytes #x1168 );; VG_MAX_IMAGE_BYTES
(export 'max-image-bytes)
(defparameter max-float #x1169 );; VG_MAX_FLOAT
(export 'max-float)
(defparameter max-gaussian-std-deviation #x116A );; VG_MAX_GAUSSIAN_STD_DEVIATION
(export 'max-gaussian-std-deviation)
;; (defparameter param-type-force-size #x7FFFFFFF );; VG_PARAM_TYPE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:523:31)
;;
(declaim (inline &get-iv))
(defcfun ("vgGetiv" &get-iv) :VOID
  "see: (/opt/vc/include/VG/openvg.h:523:31)"
  (type  param-type) ;; type #<typedef VGParamType>
  (count  XFIXNUM) ;; count #<typedef VGint>
  (values  (:pointer :INT)) ;; values #<POINTER #<typedef VGint>>
)
(export '&get-iv)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:522:31)
;;
(declaim (inline &get-fv))
(defcfun ("vgGetfv" &get-fv) :VOID
  "see: (/opt/vc/include/VG/openvg.h:522:31)"
  (type  param-type) ;; type #<typedef VGParamType>
  (count  XFIXNUM) ;; count #<typedef VGint>
  (values  (:pointer :FLOAT)) ;; values #<POINTER #<typedef VGfloat>>
)
(export '&get-fv)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:521:32)
;;
(declaim (inline &get-vector-size))
(defcfun ("vgGetVectorSize" &get-vector-size) :INT
  "see: (/opt/vc/include/VG/openvg.h:521:32)"
  (type  param-type) ;; type #<typedef VGParamType>
)
(export '&get-vector-size)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:520:32)
;;
(declaim (inline &get-i))
(defcfun ("vgGeti" &get-i) :INT
  "see: (/opt/vc/include/VG/openvg.h:520:32)"
  (type  param-type) ;; type #<typedef VGParamType>
)
(export '&get-i)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:519:34)
;;
(declaim (inline &get-f))
(defcfun ("vgGetf" &get-f) :FLOAT
  "see: (/opt/vc/include/VG/openvg.h:519:34)"
  (type  param-type) ;; type #<typedef VGParamType>
)
(export '&get-f)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:516:31)
;;
(declaim (inline &set-iv))
(defcfun ("vgSetiv" &set-iv) :VOID
  "see: (/opt/vc/include/VG/openvg.h:516:31)"
  (type  param-type) ;; type #<typedef VGParamType>
  (count  XFIXNUM) ;; count #<typedef VGint>
  (values  (:pointer :INT)) ;; values #<POINTER #<typedef VGint>>
)
(export '&set-iv)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:514:31)
;;
(declaim (inline &set-fv))
(defcfun ("vgSetfv" &set-fv) :VOID
  "see: (/opt/vc/include/VG/openvg.h:514:31)"
  (type  param-type) ;; type #<typedef VGParamType>
  (count  XFIXNUM) ;; count #<typedef VGint>
  (values  (:pointer :FLOAT)) ;; values #<POINTER #<typedef VGfloat>>
)
(export '&set-fv)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:513:31)
;;
(declaim (inline &set-i))
(defcfun ("vgSeti" &set-i) :VOID
  "see: (/opt/vc/include/VG/openvg.h:513:31)"
  (type  param-type) ;; type #<typedef VGParamType>
  (value  :INT) ;; value #<typedef VGint>
)
(export '&set-i)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:512:31)
;;
(declaim (inline &set-f))
(defcfun ("vgSetf" &set-f) :VOID
  "see: (/opt/vc/include/VG/openvg.h:512:31)"
  (type  param-type) ;; type #<typedef VGParamType>
  (value  :FLOAT) ;; value #<typedef VGfloat>
)
(export '&set-f)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:509:31)
;;
(declaim (inline &finish))
(defcfun ("vgFinish" &finish) :VOID
  "see: (/opt/vc/include/VG/openvg.h:509:31)"
)
(export '&finish)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:508:31)
;;
(declaim (inline &flush))
(defcfun ("vgFlush" &flush) :VOID
  "see: (/opt/vc/include/VG/openvg.h:508:31)"
)
(export '&flush)


;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:73:9)
;;
(defctype error-code xfixnum);; was _VGErrorCode
(export 'error-code)
(defparameter no-error #x0 );; VG_NO_ERROR
(export 'no-error)
(defparameter bad-handle-error #x1000 );; VG_BAD_HANDLE_ERROR
(export 'bad-handle-error)
(defparameter illegal-argument-error #x1001 );; VG_ILLEGAL_ARGUMENT_ERROR
(export 'illegal-argument-error)
(defparameter out-of-memory-error #x1002 );; VG_OUT_OF_MEMORY_ERROR
(export 'out-of-memory-error)
(defparameter path-capability-error #x1003 );; VG_PATH_CAPABILITY_ERROR
(export 'path-capability-error)
(defparameter unsupported-image-format-error #x1004 );; VG_UNSUPPORTED_IMAGE_FORMAT_ERROR
(export 'unsupported-image-format-error)
(defparameter unsupported-path-format-error #x1005 );; VG_UNSUPPORTED_PATH_FORMAT_ERROR
(export 'unsupported-path-format-error)
(defparameter image-in-use-error #x1006 );; VG_IMAGE_IN_USE_ERROR
(export 'image-in-use-error)
(defparameter no-context-error #x1007 );; VG_NO_CONTEXT_ERROR
(export 'no-context-error)
;; (defparameter error-code-force-size #x7FFFFFFF );; VG_ERROR_CODE_FORCE_SIZE
;;------------------------------------------------------------------------------
;; (/opt/vc/include/VG/openvg.h:506:38)
;;
(declaim (inline &get-error))
(defcfun ("vgGetError" &get-error) error-code
  "see: (/opt/vc/include/VG/openvg.h:506:38)"
)
(export '&get-error)
